name: generate_readme
run-name: Generate README
on:
  push:
    paths:
      - 'pmx_data/*/info.ya?ml'
      - 'pmx_data/*/custom_writeup.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 
      uses: actions/checkout@v2

    - name: Get list of changed files  
      uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: shell
        filters: |
          info:
            - added|modified: 'pmx_data/**/info.yaml'

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Download required libraries
      run: pip install snakemd pyyaml
        
    - name: Generate README
      run: python generate_readme.py ${{ steps.extract_branch.outputs.branch }}
    
    - name: Generate sub-README
      run: python generate_sub_readme.py ${{ steps.filter.outputs.info_files }}

    - name: Commit README
      continue-on-error: true
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Regenerated README"
        git push